### ISSUE TITLE
Hover tip is not displayed

### ISSUE THREAD

**Issue by joelson-c** [cweijan/autohotkey-plus#71]
VS Code Version: 1.54.3 (user setup)
OS: Windows_NT x64 10.0.19042
AHK Version: 1.1.33.06

When hovering any method call or command the hover tip is not displayed.

Apparently, there is something related to the [tryGetSnippetHover function](https://github.com/AutoHotkey-Plus/vscode-autohotkey/blob/master/src/providers/ahkHoverProvider.ts#L52). If the `MarkdownString` constructor is called with an empty string as initial value, rather than `null`, the hover tip works as expected.

<details>
<summary>Extension Host Log messages</summary>

````
[2021-03-18 13:16:40.856] [exthost] [error] [cweijan.vscode-autohotkey-plus] provider FAILED
[2021-03-18 13:16:40.856] [exthost] [error] Error: Illegal argument: value
	at Object.k [as illegalArgument] (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new C (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:60:18047)
	at new s (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:81:27213)
	at new s (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:81:11705)
	at AhkHoverProvider.tryGetSnippetHover (c:\Users\joels\.vscode\extensions\cweijan.vscode-autohotkey-plus-2.6.2\out\providers\ahkHoverProvider.js:46:29)
	at AhkHoverProvider.<anonymous> (c:\Users\joels\.vscode\extensions\cweijan.vscode-autohotkey-plus-2.6.2\out\providers\ahkHoverProvider.js:24:39)
	at Generator.next (<anonymous>)
	at c:\Users\joels\.vscode\extensions\cweijan.vscode-autohotkey-plus-2.6.2\out\providers\ahkHoverProvider.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\joels\.vscode\extensions\cweijan.vscode-autohotkey-plus-2.6.2\out\providers\ahkHoverProvider.js:4:12)
	at AhkHoverProvider.provideHover (c:\Users\joels\.vscode\extensions\cweijan.vscode-autohotkey-plus-2.6.2\out\providers\ahkHoverProvider.js:22:16)
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:156761
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:7538
	at new Promise (<anonymous>)
	at Object.g [as asPromise] (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:7510)
	at n.provideHover (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:156732)
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:179262
	at Se._withAdapter (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:176060)
	at Se.$provideHover (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:179238)
	at c._doInvokeHandler (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:10509)
	at c._invokeHandler (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:10201)
	at c._receiveRequest (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:8820)
	at c._receiveOneMessage (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:7673)
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:5782
	at g.fire (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at p.fire (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15443)
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29119
	at g.fire (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at p.fire (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15443)
	at t._receiveMessage (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20693)
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17587
	at g.fire (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at l.acceptChunk (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12808)
	at c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12156
	at Socket.E (c:\Users\joels\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
````

</details>

**Comment by mark-wiemer** [comment]
Your diagnosis is correct, and this issue is solved in my fork, AutoHotkey Plus Plus! Feel free to check out [mark-wiemer/vscode-autohotkey-plus-plus#16](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/16) for more info on how I solved the issue. My extension is available to install through all the regular means, including the VS Code extensions view :)

**Comment by mark-wiemer** [comment]
Fixed in v3 :)
